spring:
  application:
    name: edutechapi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/edutechapidb
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
    com.edutech.api: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"